### ISSUE TITLE
Gives Logins But They Dont Work

### ISSUE THREAD

**Issue by Catchii** [TerrificTable/Roblox-Account-Gen#1]
help lol

**Comment by Catchii** [comment]
> are you running the program headless? if yes its the problem that 1. the usernames are invalid or you need to fill out the captcha yourself, i dont have a working captcha bypass rn

I don't I complete 1 captcha on 1 browser and then it completes like 5 accs but only the 1 works I did the captcha on

**Comment by Catchii** [comment]
And btw I got an suggestion could u maybe somehow Code so it gives u the login details and .roblosecurity cookie? Would be mad op lol

**Comment by TerrificTable** [comment]
i have no clue then

> > are you running the program headless? if yes its the problem that 1. the usernames are invalid or you need to fill out the captcha yourself, i dont have a working captcha bypass rn
> 
> I don't I complete 1 captcha on 1 browser and then it completes like 5 accs but only the 1 works I did the captcha on

**Comment by TerrificTable** [comment]
> And btw I got an suggestion could u maybe somehow Code so it gives u the login details and .roblosecurity cookie? Would be mad op lol

i can try to do that

**Comment by Catchii** [comment]
> are you running the program headless? if yes its the problem that 1. the usernames are invalid or you need to fill out the captcha yourself, i dont have a working captcha bypass rn

Funcaptchasolver.py

**Comment by TerrificTable** [comment]
> > are you running the program headless? if yes its the problem that 1. the usernames are invalid or you need to fill out the captcha yourself, i dont have a working captcha bypass rn
> 
> Funcaptchasolver.py
> 
> 

Where?
