### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by untitledmp3** [TerrificTable/Roblox-Account-Gen#3]
Traceback (most recent call last):
  File "D:\Mika\Desktop\h\main.py", line 29, in <module>
    from util.singeCheckerModule import mainChecker
  File "D:\Mika\Desktop\h\util\singeCheckerModule.py", line 4, in <module>
    from main import main
  File "D:\Mika\Desktop\h\main.py", line 29, in <module>
    from util.singeCheckerModule import mainChecker
ImportError: cannot import name 'mainChecker' from 'util.singeCheckerModule' (D:\Mika\Desktop\h\util\singeCheckerModule.py)

No clue what this means

**Comment by TerrificTable** [comment]
1. how did you execute the file like just rightclick and open or did you executed it with vscode 2. that file shouldnt be implemented 3. that module doesnt rly work

**Comment by TerrificTable** [comment]
Schould be fixed with the New Version
